name: appdynamics_mobilesdk
description: A flutter plugin to integrate AppDynamics Mobile Real User Monitoring with your application.
version: 1.0.0
homepage: https://github.com/Appdynamics/flutter-plugin/
issue_tracker: https://github.com/Appdynamics/flutter-plugin/issues

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.appdynamics.appdynamics_mobilesdk
        pluginClass: AppdynamicsMobilesdkPlugin
      ios:
        pluginClass: AppdynamicsMobilesdkPlugin
